### ISSUE TITLE
Module naming conflict

### ISSUE THREAD

**Issue by inspmoore** [danceyoung/react-native-selectmultiple-button#3]
After adding react-native-selectmultiple-button to the project the compiler spitted out this error:

jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-animated
  Paths: /Users/MoorePro/Devs/Project/scaffolding/node_modules/react-native-selectmultiple-button/node_modules/react-native/Libraries/Animated/release/package.json collides with /Users/MoorePro/Devs/Project/scaffolding/node_modules/react-native/Libraries/Animated/release/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
ERROR
23:11
jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-animated
  Paths: /Users/MoorePro/Devs/Project/scaffolding/node_modules/react-native-selectmultiple-button/node_modules/react-native/Libraries/Animated/release/package.json collides with /Users/MoorePro/Devs/Project/scaffolding/node_modules/react-native/Libraries/Animated/release/package.json

This error is caused by a @providesModule declaration with the same name across two different files.

I'm running this on expo 2.4.0, nodejs 10.13.0

**Comment by danceyoung** [comment]
react-native-selectmultiple-button pacage does not contain Animated package.
You try deleting the folder node_modules within your project scaffloding, then npm install again

**Comment by inspmoore** [comment]
Thanks @danceyoung for the reply. I tried it already and unfortunately this doesn't resolve the issue. The conflict is still there. Any other ideas?

**Comment by danceyoung** [comment]
@inspmoore Can you send a demo to my email danceyoung@hotmail.com.
Thanks

**Comment by ScottWallace** [comment]
For those who believe instead in the power of Github comments for issues' ability to serve a solution for everyone, instead of email, here's a temporary patch until the developer takes the time to fix this issue or deprecates the project.

Create a new file in the root of your project, called `rn-cli.config.js` and add this to it:

```
module.exports = {
  resolver: {
    blacklistRE: /node_modules\/.*\/node_modules\/react-native\/.*/,
  }
 };
```
From:
https://github.com/facebook/react-native/issues/21242#issuecomment-445784118

_Note: If you're on Windows (bless your heart), you'll need a different pathing.  Read further in the comments for that issue to see a recommendation that I've not tried, because I'm on a real computer._

Again, this is a temporary fix, not a solution.  For the solution, fork the code, take five more minutes to study the problem, apply the package.json fix, then email all your friends.  No, wait, don't email them, there's better ways.  Like Github comments.

Anyhoo, for the God knows how many who quickly tried this very broken and abandoned project and walked away without emailing the developer for the solution, here's hoping you'll come back and read this.  It's an excellent component, and I hope the developer will apply his emailed solution to it.

That's right, I'm lightheartedly gigging the developer for his use of email for support.  Let's not do that.  Email support is an abomination that Github is meant to solve.
